### ISSUE TITLE
Copy of novnc/websockify?

### ISSUE THREAD

**Issue by evantobin** [maximegris/node-websockify#4]
I'm wondering if this is a copy of novnc/websockify or an original work. A lot of the code is the same, however, it has a different license.

**Comment by CraigZych** [comment]
It's clearly based on the concept of novnc/websockify based on the name and similar functionality. 
The code however can not be claimed to be the same since one is python and the other is js. 
Even if written in a similar style they are completely different and I would say just in having different licenses.

**Comment by evantobin** [comment]
There is a JS version of websockify and several lines in this repo match it
exactly. I’m just wondering if that’s pure coincidence as then this repo
would serve as an acceptable alternative.
https://github.com/novnc/websockify/blob/master/other/js/websockify.js

**Comment by CraigZych** [comment]
Fair enough. I've never noticed that js version. Does seem quite similar beyond coincidence in many spots.

**Comment by evantobin** [comment]
If you’ve never noticed the JS version, that’s good enough for me. I just
have to do my due diligence in terms of determining whether this repo is
just a fork of it with the wrong license which it is not.

**Comment by CraigZych** [comment]
Well it's not my repository to comment on where the original code came from. I have just used it so thought I'd chime in on the js version vs the python version. 
Now I see your comparing js to js. Different story.

**Comment by evantobin** [comment]
Ah! I’m replying via email so I didn’t notice you aren’t the owner of the
repo. I’ll have to wait for @maximegris to respond.

**Comment by maximegris** [comment]
Hi! 
Indeed this (old) project is inspired of websockify JS. I didn't directly forked the project because I was only concerned by the JS sample.

I changed the licence to LGPLv3 and I edited the readme with a link to websockify to clarify more :)
